Change in installation process

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -14,14 +14,15 @@ then
     exit
 fi
 
+dbg installer "Checking out latest version..."
+git checkout tags/$TERMEX || die 1 "Git checkout failed."
+
 dbg installer "Copying files..."
 mkdir ~/.termex
-cp . ~/.termex || die 1 "Copying failed."
-cd ~/.termex
-git checkout tags/$TERMEX || die 2 "Git checkout failed."
+cp -r . ~/.termex || die 2 "Copying failed."
 
 dbg installer "Finishing up installation..."
 cat ~/.bashrc > "$(mktemp -p ~ .bashrc.XXXXXXXX)"
-echo -e "\nexport PATH=\"$PATH:~/.termex/bin\"" >> ~/.bashrc
+echo -e "\nexport PATH=\"\$PATH:$(readlink -f ~/.termex/bin)\"" >> ~/.bashrc
 
 dbg installer "Installation finished."
